<#
.SYNOPSIS
    Initialize the local artifacts folder structure for agent session outputs.

.DESCRIPTION
    Creates the standard artifacts directory hierarchy for storing plans, reviews,
    research, security audits, and session state. Designed to be called by agents
    when working in any repository that references the central orchestrator.

.PARAMETER RepositoryRoot
    Path to the repository root. Defaults to current directory.

.PARAMETER SessionId
    Optional session identifier for tracking. Auto-generated if not provided.

.EXAMPLE
    pwsh -File scripts/init-artifacts.ps1

.EXAMPLE
    pwsh -File scripts/init-artifacts.ps1 -RepositoryRoot "C:\Projects\my-app" -SessionId "2025-06-20-feat-auth"
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$RepositoryRoot = (Get-Location).Path,

    [Parameter()]
    [string]$SessionId = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Define artifacts structure
$artifactsPath = Join-Path $RepositoryRoot "artifacts"
$subfolders = @(
    "plans",
    "reviews",
    "research",
    "decisions",
    "sessions",
    "tests",
    "specs",
    "memory",
    ".archive"
)

# Create main artifacts folder
if (-not (Test-Path $artifactsPath)) {
    New-Item -ItemType Directory -Path $artifactsPath -Force | Out-Null
    Write-Host "[OK] Created: $artifactsPath" -ForegroundColor Green
} else {
    Write-Host "[INFO] Exists: $artifactsPath" -ForegroundColor Cyan
}

# Create subfolders
foreach ($folder in $subfolders) {
    $folderPath = Join-Path $artifactsPath $folder
    if (-not (Test-Path $folderPath)) {
        New-Item -ItemType Directory -Path $folderPath -Force | Out-Null
        Write-Host "[OK] Created: $folderPath" -ForegroundColor Green
    } else {
        Write-Host "[INFO] Exists: $folderPath" -ForegroundColor Cyan
    }
}

# Create README
$readmePath = Join-Path $artifactsPath "README.md"
if (-not (Test-Path $readmePath)) {
    $readmeLines = @(
        "# Agent Artifacts",
        "",
        "This folder contains outputs from the Copilot Orchestrator agents.",
        "",
        "## Structure",
        "",
        "| Folder | Agent | Purpose |",
        "|--------|-------|---------|",
        "| ``plans/`` | Planner, Implementer, Conductor | Implementation plans and phase completions |",
        "| ``reviews/`` | Reviewer | Code review verdicts and findings |",
        "| ``research/`` | Researcher | Research briefs, citations, and analysis |",
        "| ``decisions/`` | Conductor | Architectural Decision Records (permanent) |",
        "| ``sessions/`` | Conductor | Session state for resume/continuity |",
        "| ``tests/`` | Test, GUI Tester | Test reports and coverage analysis |",
        "| ``specs/`` | Conductor | Project specifications |",
        "| ``memory/`` | Conductor | Active context and session memory |",
        "",
        "## Naming Conventions",
        "",
        "- **Plans**: ``plans/{feature-slug}/plan.md``",
        "- **Reviews**: ``reviews/{YYYY-MM-DD}-{feature-slug}.md``",
        "- **Research**: ``research/{topic-slug}.md``",
        "- **Security**: ``security/{YYYY-MM-DD}-{scope-slug}.md``",
        "- **Sessions**: ``sessions/{session-id}.json``",
        "- **Other Reports**: ``{folder}/{YYYY-MM-DD}-{slug}.md``",
        "",
        "## Generated By",
        "",
        "[Copilot Orchestrator](https://github.com/your-org/copilot-orchestrator)",
        "",
        "---",
        "*This folder is auto-generated. Do not manually modify session state files.*"
    )
    $readmeContent = $readmeLines -join "`r`n"
    Set-Content -Path $readmePath -Value $readmeContent -Encoding UTF8
    Write-Host "Created: $readmePath" -ForegroundColor Green
}

# Create .gitignore for artifacts
$gitignorePath = Join-Path $artifactsPath ".gitignore"
if (-not (Test-Path $gitignorePath)) {
    $gitignoreLines = @(
        "# Ignore session state (may contain sensitive context)",
        "sessions/*.json",
        "",
        "# Ignore temporary files",
        "*.tmp",
        "*.bak",
        "",
        "# Keep structure files",
        "!.gitkeep",
        "!README.md"
    )
    $gitignoreContent = $gitignoreLines -join "`r`n"
    Set-Content -Path $gitignorePath -Value $gitignoreContent -Encoding UTF8
    Write-Host "Created: $gitignorePath" -ForegroundColor Green
}

# Create .gitkeep files to preserve empty folders
foreach ($folder in $subfolders) {
    $folderPath = Join-Path $artifactsPath $folder
    $gitkeepPath = Join-Path $folderPath ".gitkeep"
    if (-not (Test-Path $gitkeepPath)) {
        New-Item -ItemType File -Path $gitkeepPath -Force | Out-Null
    }
}

# Create wiki knowledge base starter pages
$wikiPath = Join-Path (Join-Path $artifactsPath "memory") "wiki"
if (-not (Test-Path $wikiPath)) {
    New-Item -ItemType Directory -Path $wikiPath -Force | Out-Null
    Write-Host "[OK] Created: $wikiPath" -ForegroundColor Green
}

$wikiPages = @(
    "codebase-patterns",
    "build-and-test",
    "lessons-learned",
    "dependencies",
    "tooling"
)

foreach ($page in $wikiPages) {
    $pagePath = Join-Path $wikiPath "$page.md"
    if (-not (Test-Path $pagePath)) {
        $titleWords = ($page -split '-') | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }
        $title = $titleWords -join ' '
        $pageContent = @("# $title", "", "<!-- Wiki page maintained by agents. One fact per bullet, date-stamped. Max 50 lines. -->", "")
        Set-Content -Path $pagePath -Value ($pageContent -join "`r`n") -Encoding UTF8
    }
}
Write-Host "[OK] Wiki pages initialized: $($wikiPages -join ', ')" -ForegroundColor Green

# Generate session ID if needed and create initial session file
if ($SessionId -eq "") {
    $SessionId = "session-$(Get-Date -Format 'yyyy-MM-dd-HHmmss')"
}

$sessionsFolder = Join-Path $artifactsPath "sessions"
$sessionFile = Join-Path $sessionsFolder "$SessionId.json"
if (-not (Test-Path $sessionFile)) {
    $sessionState = @{
        sessionId = $SessionId
        created = (Get-Date -Format "o")
        repository = $RepositoryRoot
        status = "initialized"
        currentPhase = "none"
        planProgress = "0 of 0"
        artifacts = @()
    } | ConvertTo-Json -Depth 3
    Set-Content -Path $sessionFile -Value $sessionState -Encoding UTF8
    Write-Host "[OK] Session initialized: $SessionId" -ForegroundColor Green
}

Write-Host ""
Write-Host "[READY] Artifacts folder ready at: $artifactsPath" -ForegroundColor Cyan
Write-Host "[SESSION] Session ID: $SessionId" -ForegroundColor Cyan
